# Local Configuration File (optional)
# This file can be used for local development overrides

http:
  addr: ":8080"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"
  max_body: 10485760
  cors_origins: ["*"]

db:
  dsn: "postgres://username:password@localhost:5432/eco_van_db?sslmode=disable"
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: "30m"
  max_conn_idle: "10m"

auth:
  jwt_secret: "your-super-secret-jwt-key-here"
  access_ttl: "15m"
  refresh_ttl: "720h"

telemetry:
  log_level: "info"
  otlp_endpoint: ""
  enable_metrics: true
  enable_tracing: false

photos:
  dir: "/photos"
